import { Roboto_Flex, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navigation from '@/components/layout/navigation';

const roboto = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} antialiased font-(family-name:--font-roboto-flex) bg-dark-main`}
      >
      <Navigation />
      {children}
      </body>
    </html>
  );
}
